### ISSUE TITLE
Request for tagged version

### ISSUE THREAD

**Issue by JesseBowling** [MattCarothers/uhp#2]
Hi @MattCarothers ! Thanks for this project. We're working to include your honeypot in our fork of MHN, https://github.com/CommunityHoneyNetwork . Currently our build processes would pull in whatever happens to be in master at the time. We'd like to get some predictability around what would be pulled in.

Do you have any plans for tagging specific commits as a version? Would you be open to tagging stable versions?

Thanks in advance and cheers!

Jesse

**Comment by MattCarothers** [comment]
Excellent idea.  Done.
